-- V10 — Payments & auto-renew lifecycle (Phase 8, Stage 1: stub-first).
-- Adds the renewal/grace/cancellation fields to subscriptions, the payments ledger
-- (one row per charge attempt, UNIQUE idempotency key), and widens the "one live sub
-- per (student, coach)" guard to also cover PAST_DUE.

-- Auto-renew lifecycle fields on subscriptions.
alter table subscriptions add column auto_renew            boolean not null default true;
alter table subscriptions add column saved_card_token      varchar(255);
alter table subscriptions add column cancelled_at          timestamp with time zone;
alter table subscriptions add column failed_charge_count   integer not null default 0;
alter table subscriptions add column last_charge_attempt_at timestamp with time zone;

-- A PAST_DUE subscription is still "live" (grace window) and must block a duplicate, so the
-- one-live-sub-per-pair guard now covers ACTIVE + PAST_DUE (was ACTIVE only in V5).
drop index uq_active_subscription_per_coach;
create unique index uq_live_subscription_per_coach
    on subscriptions (student_user_id, coach_profile_id)
    where status in ('ACTIVE', 'PAST_DUE');

-- Payments ledger. One row per charge attempt; refunds (deferred) will be NEW rows
-- (type=REFUND, source_payment_id -> original) — never a mutation of an existing row.
create table payments (
    id                  bigint generated by default as identity primary key,
    subscription_id     bigint                   not null references subscriptions (id),
    type                varchar(20)              not null,
    amount              numeric(12, 2)           not null,
    status              varchar(20)              not null,
    -- Double-charge guard: at most one row per logical charge attempt.
    idempotency_key     varchar(200)             not null,
    provider_reference  varchar(255),
    -- Commission snapshot at transaction time. rate is a fraction (e.g. 0.2000).
    commission_rate     numeric(5, 4)            not null,
    commission_amount   numeric(12, 2)           not null,
    coach_payout_amount numeric(12, 2)           not null,
    source_payment_id   bigint                            references payments (id),
    created_at          timestamp with time zone not null,
    updated_at          timestamp with time zone not null,
    version             bigint                   not null default 0,
    constraint uq_payments_idempotency_key unique (idempotency_key)
);

create index idx_payments_subscription on payments (subscription_id);
