-- V12 — KVKK / safety minimum (Phase 8)

alter table users add column suspension_reason varchar(2000);

create table consent_records (
    id               bigint generated by default as identity primary key,
    user_id          bigint                   not null references users (id),
    consent_type     varchar(50)              not null,
    document_version varchar(50)              not null,
    accepted_at      timestamp with time zone not null,
    ip_address       varchar(100),
    user_agent       varchar(500),
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    version          bigint                   not null default 0
);

create table reports (
    id                   bigint generated by default as identity primary key,
    reporter_user_id     bigint                   not null references users (id),
    target_type          varchar(50)              not null,
    target_id            bigint                   not null,
    reason               varchar(2000)            not null,
    details              varchar(4000),
    status               varchar(50)              not null,
    created_at           timestamp with time zone not null,
    updated_at           timestamp with time zone not null,
    reviewed_at          timestamp with time zone,
    reviewed_by_admin_id bigint                   references users (id),
    version              bigint                   not null default 0
);

create index idx_reports_status_created_at on reports (status, created_at desc);

create table admin_conversation_access_logs (
    id              bigint generated by default as identity primary key,
    admin_user_id   bigint                   not null references users (id),
    conversation_id bigint                   not null references conversations (id),
    reason          varchar(2000)            not null,
    accessed_at     timestamp with time zone not null,
    created_at      timestamp with time zone not null,
    updated_at      timestamp with time zone not null,
    version         bigint                   not null default 0
);
