-- V18 — Create OAuth2 login codes for secure exchange flow.

create table oauth2_login_codes (
    id          bigint generated by default as identity primary key,
    user_id     bigint                   not null references users (id) on delete cascade,
    code_hash   varchar(64)              not null,
    expires_at  timestamp with time zone not null,
    consumed_at timestamp with time zone,
    created_at  timestamp with time zone not null,
    updated_at  timestamp with time zone not null,
    version     bigint                   not null default 0,
    constraint uq_oauth2_login_codes_code_hash unique (code_hash)
);

create index idx_oauth2_login_codes_user_id on oauth2_login_codes (user_id);
create index idx_oauth2_login_codes_expires_at on oauth2_login_codes (expires_at);
