-- Versioned legal documents and immutable user acceptance evidence.

alter table users add column legal_onboarding_completed boolean not null default false;
-- Existing accounts predate this foundation. Preserve their product access; only newly
-- provisioned OAuth accounts are held for explicit legal onboarding.
update users set legal_onboarding_completed = true;

create table legal_documents (
    id                        bigint generated by default as identity primary key,
    type                      varchar(60)              not null,
    document_version          varchar(50)              not null,
    title                     varchar(300)             not null,
    content                   text                     not null,
    content_hash              varchar(64)              not null,
    status                    varchar(20)              not null,
    required_for_registration boolean                  not null default false,
    published_at              timestamp with time zone,
    effective_at              timestamp with time zone,
    created_at                timestamp with time zone not null,
    updated_at                timestamp with time zone not null,
    version                   bigint                   not null default 0,
    constraint uq_legal_document_type_version unique (type, document_version),
    constraint ck_legal_document_publish_dates check (
        status <> 'PUBLISHED' or (published_at is not null and effective_at is not null))
);

create unique index uq_legal_documents_one_published_per_type
    on legal_documents(type) where status = 'PUBLISHED';
create index idx_legal_documents_public_lookup on legal_documents(type, status, effective_at desc);

create table legal_acceptances (
    id                    bigint generated by default as identity primary key,
    user_id               bigint                   not null references users(id),
    legal_document_id     bigint                   not null references legal_documents(id),
    document_type         varchar(60)              not null,
    document_version      varchar(50)              not null,
    document_content_hash varchar(64)              not null,
    acceptance_type       varchar(30)              not null,
    accepted_at           timestamp with time zone not null,
    withdrawn_at          timestamp with time zone,
    source                varchar(50)              not null,
    created_at            timestamp with time zone not null,
    updated_at            timestamp with time zone not null,
    version               bigint                   not null default 0
);

create unique index uq_legal_acceptances_active_evidence
    on legal_acceptances(user_id, legal_document_id, acceptance_type, source)
    where withdrawn_at is null;
create index idx_legal_acceptances_user on legal_acceptances(user_id, accepted_at desc);

-- Placeholder-only content. The legal team must replace each document with approved text.
insert into legal_documents
    (type, document_version, title, content, content_hash, status, required_for_registration,
     published_at, effective_at, created_at, updated_at, version)
values
('KVKK_NOTICE', '1.0', 'KVKK Aydınlatma Metni (Taslak Yer Tutucu)',
 'PLACEHOLDER: Final KVKK Notice text will be supplied by the legal team.',
 'b3948492f9466aacd207ecf61eb11d5f697c354387c906d7d4955eda7627b20e', 'PUBLISHED', false,
 current_timestamp, current_timestamp, current_timestamp, current_timestamp, 0),
('EXPLICIT_CONSENT', '1.0', 'Açık Rıza Metni (Taslak Yer Tutucu)',
 'PLACEHOLDER: Final Explicit Consent text will be supplied by the legal team.',
 'dd43d27ed288adc366b7b97d2676e52e8a222d08ab7cd9027d4e943124e959e1', 'PUBLISHED', true,
 current_timestamp, current_timestamp, current_timestamp, current_timestamp, 0),
('TERMS_OF_USE', '1.0', 'Kullanım Koşulları (Taslak Yer Tutucu)',
 'PLACEHOLDER: Final Terms of Use text will be supplied by the legal team.',
 '35fb42910b5fc6a1d740e94fd811165a1c1f7e5159a2759027b7d0e1f96558ea', 'PUBLISHED', true,
 current_timestamp, current_timestamp, current_timestamp, current_timestamp, 0),
('PRIVACY_POLICY', '1.0', 'Gizlilik Politikası (Taslak Yer Tutucu)',
 'PLACEHOLDER: Final Privacy Policy text will be supplied by the legal team.',
 '29058187c9c8c50c9184e05f0cdeae52f6fd028811634ddf0cc9bcb63b0b529a', 'PUBLISHED', false,
 current_timestamp, current_timestamp, current_timestamp, current_timestamp, 0),
('COOKIE_POLICY', '1.0', 'Çerez Politikası (Taslak Yer Tutucu)',
 'PLACEHOLDER: Final Cookie Policy text will be supplied by the legal team.',
 'f445ce6e431691ade678fc1adf0677772c6a8e57ba589901364d77a69b2effcb', 'PUBLISHED', false,
 current_timestamp, current_timestamp, current_timestamp, current_timestamp, 0);
