-- Channel-specific marketing choices, authenticated cookie preferences and controlled account deletion.

create table marketing_preferences (
    id            bigint generated by default as identity primary key,
    user_id       bigint                   not null references users(id),
    channel       varchar(20)              not null,
    status        varchar(20)              not null,
    granted_at    timestamp with time zone,
    withdrawn_at  timestamp with time zone,
    source         varchar(50)              not null,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null,
    version        bigint                   not null default 0,
    constraint uq_marketing_preferences_user_channel unique (user_id, channel),
    constraint ck_marketing_preferences_channel check (channel in ('EMAIL', 'SMS')),
    constraint ck_marketing_preferences_status check (status in ('GRANTED', 'WITHDRAWN')),
    constraint ck_marketing_preferences_timestamps check (
        (status = 'GRANTED' and granted_at is not null and withdrawn_at is null)
        or (status = 'WITHDRAWN' and withdrawn_at is not null)
    )
);

create index idx_marketing_preferences_user_status
    on marketing_preferences(user_id, status);

create table privacy_preferences (
    id                        bigint generated by default as identity primary key,
    user_id                   bigint                   not null references users(id),
    analytics_allowed         boolean                  not null default false,
    marketing_allowed         boolean                  not null default false,
    cookie_policy_document_id bigint                   not null references legal_documents(id),
    policy_version            varchar(50)              not null,
    granted_at                timestamp with time zone not null,
    source                    varchar(50)              not null,
    created_at                timestamp with time zone not null,
    updated_at                timestamp with time zone not null,
    version                   bigint                   not null default 0,
    constraint uq_privacy_preferences_user unique (user_id)
);

create index idx_privacy_preferences_policy
    on privacy_preferences(cookie_policy_document_id);

create table account_deletion_requests (
    id                    bigint generated by default as identity primary key,
    user_id               bigint                   not null references users(id),
    status                varchar(20)              not null,
    requested_at          timestamp with time zone not null,
    completed_at          timestamp with time zone,
    failure_reason        varchar(1000),
    processing_source     varchar(50)              not null,
    identity_email_hash   varchar(64)              not null,
    oauth_subject_hash    varchar(64),
    created_at            timestamp with time zone not null,
    updated_at            timestamp with time zone not null,
    version               bigint                   not null default 0,
    constraint uq_account_deletion_requests_user unique (user_id),
    constraint uq_account_deletion_identity_email unique (identity_email_hash),
    constraint ck_account_deletion_status check (
        status in ('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    constraint ck_account_deletion_completed_at check (
        (status = 'COMPLETED' and completed_at is not null)
        or (status <> 'COMPLETED' and completed_at is null))
);

create unique index uq_account_deletion_oauth_subject
    on account_deletion_requests(oauth_subject_hash) where oauth_subject_hash is not null;
create index idx_account_deletion_user_status
    on account_deletion_requests(user_id, status);

-- A deleted coach's education reference is profile PII and must be clearable.
alter table coach_profiles alter column university_id drop not null;
