alter table users add column password_changed_at timestamp with time zone;
alter table users add column password_version integer not null default 0;

create table password_reset_tokens (
    id         bigint generated by default as identity primary key,
    user_id    bigint                   not null references users(id),
    token_hash varchar(64)              not null,
    expires_at timestamp with time zone not null,
    used_at    timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version    bigint                   not null default 0,
    constraint uq_password_reset_tokens_hash unique (token_hash)
);

create index idx_password_reset_tokens_user on password_reset_tokens(user_id);
create index idx_password_reset_tokens_expiry on password_reset_tokens(expires_at);
create index idx_password_reset_tokens_active_hash on password_reset_tokens(token_hash)
    where used_at is null;
