create table email_verification_codes (
    id            bigint generated by default as identity primary key,
    user_id       bigint                   not null references users(id),
    code_hash     varchar(100)             not null,
    expires_at    timestamp with time zone not null,
    used_at       timestamp with time zone,
    attempt_count integer                  not null default 0,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null,
    version       bigint                   not null default 0
);

create index idx_email_verification_codes_user_created
    on email_verification_codes(user_id, created_at desc);
create index idx_email_verification_codes_expiry
    on email_verification_codes(expires_at);
create index idx_email_verification_codes_active_user
    on email_verification_codes(user_id) where used_at is null;
