create table trial_consultations (
    id               bigint generated by default as identity primary key,
    coach_profile_id bigint                   not null references coach_profiles(id),
    student_user_id  bigint                   not null references users(id),
    availability_id  bigint                            references coach_availabilities(id),
    start_time       timestamp with time zone not null,
    end_time         timestamp with time zone not null,
    status           varchar(20)              not null,
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    version          bigint                   not null default 0,
    constraint ck_trial_consultation_status check
        (status in ('REQUESTED','CONFIRMED','CANCELLED','COMPLETED','NO_SHOW')),
    constraint uq_trial_consultation_availability unique (availability_id)
);

create index idx_trial_consultations_coach_start
    on trial_consultations(coach_profile_id, start_time);
create index idx_trial_consultations_student_start
    on trial_consultations(student_user_id, start_time);

-- MVP rule: at most one non-cancelled trial consultation per student/coach pair.
create unique index uq_active_trial_per_student_coach
    on trial_consultations(student_user_id, coach_profile_id)
    where status <> 'CANCELLED';
