-- Canonical successful charge timestamp. Existing successful ledger rows are backfilled from
-- their last persisted state transition; all new successes stamp this explicitly in application code.
alter table payments add column succeeded_at timestamp with time zone;
update payments set succeeded_at = updated_at where status = 'SUCCESS';
create index idx_payments_success_purchase on payments (subscription_id, succeeded_at)
    where type = 'CHARGE' and status = 'SUCCESS';

-- Student request/admin decision workflow. Financial refunds remain separate payments(type=REFUND).
create table refund_requests (
    id                             bigint generated by default as identity primary key,
    student_user_id                bigint not null references users(id),
    subscription_id                bigint not null references subscriptions(id),
    original_payment_id            bigint not null references payments(id),
    requested_at                   timestamp with time zone not null,
    purchase_at                    timestamp with time zone not null,
    refund_window                  varchar(30) not null,
    status                         varchar(20) not null,
    service_started                boolean not null,
    paid_sessions_count            integer not null,
    completed_sessions_count       integer not null,
    earliest_paid_session_at       timestamp with time zone,
    latest_relevant_session_status varchar(20),
    admin_decision_at              timestamp with time zone,
    admin_decision_by              bigint references users(id),
    rejection_reason               varchar(2000),
    refund_payment_id              bigint references payments(id),
    created_at                     timestamp with time zone not null,
    updated_at                     timestamp with time zone not null,
    version                        bigint not null default 0,
    constraint ck_refund_request_window check
        (refund_window in ('UNCONDITIONAL','STANDARD_ELIGIBLE','MANUAL_REVIEW')),
    constraint ck_refund_request_status check
        (status in ('PENDING','APPROVED','REJECTED','REFUNDED')),
    constraint ck_refund_request_counts check
        (paid_sessions_count >= 0 and completed_sessions_count >= 0
         and completed_sessions_count <= paid_sessions_count)
);

create unique index uq_active_refund_request_per_payment
    on refund_requests(original_payment_id) where status in ('PENDING','APPROVED');
create index idx_refund_requests_student_requested on refund_requests(student_user_id, requested_at desc);
create index idx_refund_requests_admin_queue on refund_requests(status, refund_window, requested_at desc);
create index idx_refund_requests_subscription on refund_requests(subscription_id);
