-- Canonical metadata for Cloudflare R2/S3-compatible object storage. Binary content and
-- temporary presigned URLs are deliberately never stored in PostgreSQL.
create table media_assets (
    id                bigint generated by default as identity primary key,
    owner_user_id     bigint                   not null references users(id),
    object_key        varchar(500)             not null,
    original_filename varchar(255),
    content_type      varchar(100)             not null,
    size_bytes        bigint                   not null,
    media_type        varchar(40)              not null,
    visibility        varchar(20)              not null,
    status            varchar(30)              not null,
    created_at        timestamp with time zone not null,
    updated_at        timestamp with time zone not null,
    version           bigint                   not null default 0,
    constraint uq_media_assets_object_key unique (object_key),
    constraint ck_media_assets_size check (size_bytes > 0),
    constraint ck_media_assets_type check (media_type in ('PROFILE_IMAGE','COACH_INTRO_VIDEO','DOCUMENT')),
    constraint ck_media_assets_visibility check (visibility in ('PUBLIC','PRIVATE')),
    constraint ck_media_assets_status check (status in ('PENDING_UPLOAD','ACTIVE','DELETED')),
    constraint ck_media_assets_visibility_by_type check
        ((media_type = 'DOCUMENT' and visibility = 'PRIVATE') or
         (media_type in ('PROFILE_IMAGE','COACH_INTRO_VIDEO') and visibility = 'PUBLIC'))
);

create index idx_media_assets_owner_status on media_assets(owner_user_id, status);
create index idx_media_assets_type_status on media_assets(media_type, status);

alter table coach_profiles add column profile_image_asset_id bigint references media_assets(id);
alter table coach_profiles add column intro_video_asset_id bigint references media_assets(id);
alter table student_profiles add column profile_image_asset_id bigint references media_assets(id);

create index idx_coach_profiles_profile_image_asset on coach_profiles(profile_image_asset_id);
create index idx_coach_profiles_intro_video_asset on coach_profiles(intro_video_asset_id);
create index idx_student_profiles_profile_image_asset on student_profiles(profile_image_asset_id);
