-- V30 — Coach applications: public "apply to become a coach" intake, reviewed by admins.
-- Distinct from coach_profiles (V4): an application has no User yet. Approval creates one.

create table coach_applications (
    id            bigint generated by default as identity primary key,
    full_name     varchar(150)             not null,
    email         varchar(255)             not null,
    phone         varchar(30),
    experience    varchar(2000),
    status        varchar(20)              not null default 'PENDING',
    reviewed_at   timestamp with time zone,
    review_note   varchar(500),
    linked_user_id bigint                  references users (id),
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null,
    version       bigint                   not null default 0
);

create index idx_coach_applications_status on coach_applications (status, created_at desc);
