-- Public media locators must never reveal the sequential media_assets primary key.
-- Two UUIDv4 values provide well above 128 bits of effective randomness for historical rows;
-- new rows receive an equally opaque token from the application service.
alter table media_assets add column public_token varchar(64);

update media_assets
set public_token = replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '')
where public_token is null;

alter table media_assets alter column public_token set not null;
alter table media_assets add constraint uq_media_assets_public_token unique (public_token);
alter table media_assets add constraint ck_media_assets_public_token_format
    check (public_token ~ '^[0-9a-f]{64}$');

-- Coach introduction videos are now admin-managed references to the official Uniform YouTube
-- channel. The historical intro_video_asset_id FK remains for data compatibility only; the
-- application no longer accepts new COACH_INTRO_VIDEO uploads or exposes those objects publicly.
alter table coach_profiles add column intro_youtube_video_id varchar(11);
alter table coach_profiles add constraint ck_coach_profiles_intro_youtube_video_id
    check (intro_youtube_video_id is null or intro_youtube_video_id ~ '^[A-Za-z0-9_-]{11}$');

-- Durable audit trail for the deliberately narrow ADMIN profile-image moderation action.
create table media_moderation_logs (
    id                   bigint generated by default as identity primary key,
    admin_user_id        bigint                   not null references users(id),
    media_asset_id       bigint                   not null references media_assets(id),
    target_owner_user_id bigint                   references users(id),
    action               varchar(40)              not null,
    reason               varchar(1000)            not null,
    moderated_at         timestamp with time zone not null,
    created_at           timestamp with time zone not null,
    updated_at           timestamp with time zone not null,
    version              bigint                   not null default 0,
    constraint ck_media_moderation_action check (action in ('REMOVE_PROFILE_IMAGE'))
);

create index idx_media_moderation_logs_asset on media_moderation_logs(media_asset_id, moderated_at desc);
create index idx_media_assets_pending_created on media_assets(status, created_at)
    where status = 'PENDING_UPLOAD';
