-- Package-management foundation. Existing package rows remain untouched for historical and
-- in-flight subscriptions, while canonical commercial prices intentionally start unconfigured.
alter table packages add column package_type varchar(30);
alter table packages add column duration_months integer;
alter table packages add column evaluation_sessions_per_month integer not null default 1;
alter table packages add column weekly_sessions_per_month integer not null default 4;
alter table packages alter column price drop not null;

alter table packages add constraint ck_packages_type check
    (package_type is null or package_type in ('ONE_MONTH','THREE_MONTHS','UNTIL_EXAM'));
alter table packages add constraint ck_packages_price_positive check (price is null or price > 0);
alter table packages add constraint ck_packages_duration_months check (duration_months is null or duration_months > 0);
alter table packages add constraint ck_packages_monthly_entitlements check
    (evaluation_sessions_per_month >= 0 and weekly_sessions_per_month >= 0);
create unique index uq_packages_package_type on packages(package_type) where package_type is not null;

insert into packages
    (name, weekly_sessions, duration_days, price, active, package_type, duration_months,
     evaluation_sessions_per_month, weekly_sessions_per_month, created_at, updated_at, version)
values
    ('1 Aylık', 1, 30, null, false, 'ONE_MONTH', 1, 1, 4, now(), now(), 0),
    ('3 Aylık', 1, 90, null, false, 'THREE_MONTHS', 3, 1, 4, now(), now(), 0),
    ('Sınava Kadar', 1, 0, null, false, 'UNTIL_EXAM', null, 1, 4, now(), now(), 0);

create table package_price_tiers (
    id               bigint generated by default as identity primary key,
    package_id       bigint not null references packages(id),
    months_remaining integer not null,
    price            numeric(12,2) not null,
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    version          bigint not null default 0,
    constraint uq_package_price_tier unique(package_id, months_remaining),
    constraint ck_package_price_tier_months check(months_remaining > 0),
    constraint ck_package_price_tier_price check(price > 0)
);

create table package_campaigns (
    id             bigint generated by default as identity primary key,
    package_id     bigint not null unique references packages(id),
    enabled        boolean not null default false,
    title          varchar(120) not null,
    description    varchar(500),
    starts_at      timestamp with time zone not null,
    ends_at        timestamp with time zone not null,
    discount_type  varchar(20) not null,
    discount_value numeric(12,2) not null,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null,
    version        bigint not null default 0,
    constraint ck_package_campaign_dates check(ends_at > starts_at),
    constraint ck_package_campaign_discount_type check(discount_type in ('PERCENTAGE','FIXED_AMOUNT')),
    constraint ck_package_campaign_discount_value check(discount_value > 0),
    constraint ck_package_campaign_percentage check(discount_type <> 'PERCENTAGE' or discount_value <= 100)
);

create table package_settings (
    id            bigint generated by default as identity primary key,
    yks_exam_date date,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null,
    version       bigint not null default 0,
    constraint ck_package_settings_singleton check(id = 1)
);
insert into package_settings(id, yks_exam_date, created_at, updated_at, version) values (1, null, now(), now(), 0);

alter table subscriptions add column package_type_snapshot varchar(30);
alter table subscriptions add column list_price_snapshot numeric(12,2);
alter table subscriptions add column effective_price_snapshot numeric(12,2);
alter table subscriptions add column campaign_title_snapshot varchar(120);
alter table subscriptions add column discount_type_snapshot varchar(20);
alter table subscriptions add column discount_value_snapshot numeric(12,2);
alter table subscriptions add column one_month_base_price_snapshot numeric(12,2);
alter table subscriptions add column purchased_at timestamp with time zone;
alter table subscriptions add column until_exam_months_remaining_snapshot integer;

alter table subscriptions add constraint ck_subscription_price_snapshots check
    ((list_price_snapshot is null or list_price_snapshot >= 0)
     and (effective_price_snapshot is null or effective_price_snapshot >= 0)
     and (one_month_base_price_snapshot is null or one_month_base_price_snapshot > 0)
     and (discount_value_snapshot is null or discount_value_snapshot > 0)
     and (until_exam_months_remaining_snapshot is null or until_exam_months_remaining_snapshot > 0));

create index idx_package_tiers_package on package_price_tiers(package_id, months_remaining);
create index idx_package_campaign_window on package_campaigns(package_id, enabled, starts_at, ends_at);
