-- V5 — Packages & Subscriptions (Phase 4a). Direct activation; payment lifecycle is Phase 8.

create table packages (
    id              bigint generated by default as identity primary key,
    name            varchar(100)             not null,
    weekly_sessions integer                  not null,
    duration_days   integer                  not null,
    price           numeric(12, 2)           not null,
    active          boolean                  not null default true,
    created_at      timestamp with time zone not null,
    updated_at      timestamp with time zone not null,
    version         bigint                   not null default 0,
    constraint uq_packages_name unique (name)
);

insert into packages (name, weekly_sessions, duration_days, price, active, created_at, updated_at, version) values
    ('Aylık 1x', 1, 30, 1500.00, true, now(), now(), 0),
    ('Aylık 2x', 2, 30, 2500.00, true, now(), now(), 0);

create table subscriptions (
    id              bigint generated by default as identity primary key,
    student_user_id bigint                   not null references users (id),
    coach_profile_id bigint                  not null references coach_profiles (id),
    package_id      bigint                   not null references packages (id),
    status          varchar(20)              not null,
    start_at        timestamp with time zone not null,
    end_at          timestamp with time zone not null,
    created_at      timestamp with time zone not null,
    updated_at      timestamp with time zone not null,
    version         bigint                   not null default 0
);

create index idx_subscriptions_student on subscriptions (student_user_id);
create index idx_subscriptions_coach on subscriptions (coach_profile_id);

-- At most one ACTIVE subscription per (student, coach) — DB-level guard against duplicates/races.
create unique index uq_active_subscription_per_coach
    on subscriptions (student_user_id, coach_profile_id)
    where status = 'ACTIVE';
