-- V9 — Messaging (Phase 5a): conversations + messages. Attachments are closed in beta.

create table conversations (
    id               bigint generated by default as identity primary key,
    student_user_id  bigint                   not null references users (id),
    coach_profile_id bigint                   not null references coach_profiles (id),
    last_message_at  timestamp with time zone not null,
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    version          bigint                   not null default 0,
    -- Exactly one thread per (student, coach).
    constraint uq_conversation_pair unique (student_user_id, coach_profile_id)
);

create index idx_conversations_student on conversations (student_user_id);
create index idx_conversations_coach on conversations (coach_profile_id);

create table messages (
    id              bigint generated by default as identity primary key,
    conversation_id bigint                   not null references conversations (id),
    sender_user_id  bigint                   not null references users (id),
    content         varchar(4000)            not null,
    read_at         timestamp with time zone,
    created_at      timestamp with time zone not null,
    updated_at      timestamp with time zone not null,
    version         bigint                   not null default 0
);

-- Supports history paging and the unread/last-message lookups.
create index idx_messages_conversation_created on messages (conversation_id, created_at);
