import React, { useEffect, useState } from "react";
import { safetyApi } from "./safetyApi";
import { ApiError } from "../api/ApiError";
import "./report-modal.css";

interface ReportModalProps { targetType:"USER"|"CONVERSATION"|"MESSAGE"; targetId:number; onClose:()=>void; onSuccess?:()=>void; }
const titles={USER:"Kullanıcıyı Bildir",CONVERSATION:"Konuşmayı Bildir",MESSAGE:"Mesajı Bildir"} as const;
const labels={USER:"Bu kullanıcı hakkında şikayet gerekçeniz",CONVERSATION:"Bu konuşma hakkında şikayet gerekçeniz",MESSAGE:"Bu mesaj hakkında şikayet gerekçeniz"} as const;

export const ReportModal:React.FC<ReportModalProps>=({targetType,targetId,onClose,onSuccess})=>{
  const [reason,setReason]=useState("Kaba / Uygunsuz Davranış"); const [details,setDetails]=useState("");
  const [isSubmitting,setIsSubmitting]=useState(false); const [errorMsg,setErrorMsg]=useState<string|null>(null); const [successMsg,setSuccessMsg]=useState<string|null>(null);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!isSubmitting)onClose()};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[isSubmitting,onClose]);
  const handleSubmit=async(event:React.FormEvent)=>{event.preventDefault();if(!reason||isSubmitting)return;setIsSubmitting(true);setErrorMsg(null);setSuccessMsg(null);try{await safetyApi.createReport(targetType,targetId,reason,details);setSuccessMsg("Bildiriminiz başarıyla iletildi. Teşekkür ederiz.");window.setTimeout(()=>{onSuccess?.();onClose()},1200)}catch(error){setErrorMsg(error instanceof ApiError?error.detail||"Bildirim gönderilirken bir hata oluştu.":"Sunucuya ulaşılamadı. Lütfen tekrar deneyin.");setIsSubmitting(false)}};
  return <div className="report-modal__backdrop" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget&&!isSubmitting)onClose()}}><section className="report-modal" role="dialog" aria-modal="true" aria-labelledby="report-modal-title"><p className="report-modal__eyebrow">Güvenlik ve destek</p><h2 id="report-modal-title">{titles[targetType]}</h2><p className="report-modal__intro">Bildiriminiz moderasyon ekibimiz tarafından gizlilikle incelenecektir.</p>{successMsg?<div className="report-modal__success" role="status">{successMsg}</div>:<form onSubmit={handleSubmit}>{errorMsg&&<div className="report-modal__error" role="alert">{errorMsg}</div>}<label htmlFor="report-reason">{labels[targetType]}<select id="report-reason" value={reason} onChange={(event)=>setReason(event.target.value)} disabled={isSubmitting}><option>Kaba / Uygunsuz Davranış</option><option>Spam veya Reklam</option><option>Taciz veya Tehdit</option><option>Sözleşme / Kural İhlali</option><option>Diğer</option></select></label><label htmlFor="report-details">Detaylar <small>İsteğe bağlı</small><textarea id="report-details" value={details} onChange={(event)=>setDetails(event.target.value.slice(0,1000))} disabled={isSubmitting} rows={5} placeholder="Bildiriminizi değerlendirmemize yardımcı olacak ayrıntıları paylaşın."/><span>{details.length}/1000</span></label><div className="report-modal__actions"><button type="button" onClick={onClose} disabled={isSubmitting}>Vazgeç</button><button className="report-modal__submit" type="submit" disabled={isSubmitting}>{isSubmitting?"Gönderiliyor…":"Bildirimi Gönder"}</button></div></form>}</section></div>;
};
