-- V1 baseline — Phase 0 skeleton.
-- No domain tables yet; the first real entities arrive in Phase 1 (Auth).
--
-- health_check is an INFRASTRUCTURE table used only to prove the Phase 0 vertical slice
-- (controller -> service -> repository -> DB). It carries the BaseEntity audit columns.

create table health_check (
    id         bigint generated by default as identity primary key,
    status     varchar(20)              not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version    bigint                   not null default 0
);

insert into health_check (status, created_at, updated_at, version)
values ('UP', now(), now(), 0);
