-- V2 — Auth (Phase 1): users + rotating refresh tokens.

create table users (
    id             bigint generated by default as identity primary key,
    email          varchar(255)             not null,
    password_hash  varchar(100),
    full_name      varchar(150)             not null,
    role           varchar(20)              not null,
    status         varchar(20)              not null,
    google_sub     varchar(255),
    email_verified boolean                  not null default false,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null,
    version        bigint                   not null default 0,
    constraint uq_users_email unique (email),
    constraint uq_users_google_sub unique (google_sub)
);

create table refresh_tokens (
    id         bigint generated by default as identity primary key,
    user_id    bigint                   not null references users (id),
    token_hash varchar(64)              not null,
    expires_at timestamp with time zone not null,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version    bigint                   not null default 0,
    constraint uq_refresh_tokens_token_hash unique (token_hash)
);

create index idx_refresh_tokens_user_id on refresh_tokens (user_id);
