-- V4 — Coach & Profile (Phase 2): universities, coach_profiles, student_profiles, coach_subjects.

create table universities (
    id         bigint generated by default as identity primary key,
    name       varchar(200)             not null,
    city       varchar(100),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version    bigint                   not null default 0,
    constraint uq_universities_name unique (name)
);

insert into universities (name, city, created_at, updated_at, version) values
    ('Boğaziçi Üniversitesi', 'İstanbul', now(), now(), 0),
    ('Orta Doğu Teknik Üniversitesi', 'Ankara', now(), now(), 0),
    ('İstanbul Teknik Üniversitesi', 'İstanbul', now(), now(), 0),
    ('Hacettepe Üniversitesi', 'Ankara', now(), now(), 0);

create table coach_profiles (
    id                   bigint generated by default as identity primary key,
    user_id              bigint                   not null references users (id),
    headline             varchar(150)             not null,
    bio                  varchar(2000),
    university_id        bigint                   not null references universities (id),
    department           varchar(150),
    graduation_year      integer,
    status               varchar(20)              not null,
    rejection_reason     varchar(500),
    active_student_count integer                  not null default 0,
    max_student_capacity integer                  not null default 10,
    payout_account_ready boolean                  not null default false,
    created_at           timestamp with time zone not null,
    updated_at           timestamp with time zone not null,
    version              bigint                   not null default 0,
    constraint uq_coach_profiles_user unique (user_id)
);

create index idx_coach_profiles_status on coach_profiles (status);

create table student_profiles (
    id          bigint generated by default as identity primary key,
    user_id     bigint                   not null references users (id),
    grade_level varchar(30),
    city        varchar(100),
    created_at  timestamp with time zone not null,
    updated_at  timestamp with time zone not null,
    version     bigint                   not null default 0,
    constraint uq_student_profiles_user unique (user_id)
);

create table coach_subjects (
    id               bigint generated by default as identity primary key,
    coach_profile_id bigint                   not null references coach_profiles (id),
    track            varchar(20)              not null,
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    version          bigint                   not null default 0,
    constraint uq_coach_subjects_profile_track unique (coach_profile_id, track)
);

create index idx_coach_subjects_track on coach_subjects (track);
