-- V6 — Coach availability slots (Phase 4b). Concrete slots only (no templates/generation).

create table coach_availabilities (
    id               bigint generated by default as identity primary key,
    coach_profile_id bigint                   not null references coach_profiles (id),
    start_time       timestamp with time zone not null,
    end_time         timestamp with time zone not null,
    is_booked        boolean                  not null default false,
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    version          bigint                   not null default 0,
    -- One slot per (coach, start) — DB-level guard against duplicate slots.
    constraint uq_availability_coach_start unique (coach_profile_id, start_time)
);

create index idx_availabilities_coach on coach_availabilities (coach_profile_id);
