-- V7 — Sessions / Booking (Phase 4c). Meet link + email are wired in Phase 4d (after-commit).

create table sessions (
    id               bigint generated by default as identity primary key,
    student_user_id  bigint                   not null references users (id),
    coach_profile_id bigint                   not null references coach_profiles (id),
    subscription_id  bigint                   not null references subscriptions (id),
    availability_id  bigint                            references coach_availabilities (id),
    status           varchar(20)              not null,
    start_time       timestamp with time zone not null,
    end_time         timestamp with time zone not null,
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    version          bigint                   not null default 0,
    -- Double-booking guard: at most one session per slot. availability_id is nullable, and
    -- Postgres treats NULLs as distinct, so cancelled sessions (link cleared) don't collide.
    constraint uq_sessions_availability unique (availability_id)
);

create index idx_sessions_student on sessions (student_user_id);
create index idx_sessions_coach on sessions (coach_profile_id);
-- Supports the weekly-quota count (subscription + status + start_time window).
create index idx_sessions_subscription_start on sessions (subscription_id, start_time);
