import { useEffect, useState } from "react";
import { adminApi } from "../../admin/adminApi";
import type { AdminUser, AdminUserDetail, UserStatus } from "../../admin/adminTypes";
import { AdminProfilePhotoModeration } from "./AdminProfilePhotoModeration";
import "./admin.css";

const labels:Record<UserStatus,string>={ACTIVE:"Aktif",SUSPENDED:"Askıya alınmış",DELETED:"Silinmiş"};

export const AdminUsersPage=()=>{
  const [users,setUsers]=useState<AdminUser[]>([]); const [selected,setSelected]=useState<AdminUserDetail|null>(null);
  const [search,setSearch]=useState(""); const [submitted,setSubmitted]=useState(""); const [status,setStatus]=useState<UserStatus|"">("");
  const [loading,setLoading]=useState(true); const [error,setError]=useState(false); const [page,setPage]=useState(0); const [pages,setPages]=useState(1);
  useEffect(()=>{let active=true;adminApi.users("STUDENT",submitted,status||undefined,page).then(r=>{if(active){setUsers(r.content??[]);setPages(Math.max(1,r.totalPages));}}).catch(()=>active&&setError(true)).finally(()=>active&&setLoading(false));return()=>{active=false};},[submitted,status,page]);
  const open=async(user:AdminUser)=>{try{setSelected(await adminApi.user(user.id));}catch{setError(true)}};
  return <main className="admin-page"><header className="admin-page__heading"><div><p className="admin-page__eyebrow">Kullanıcı yönetimi</p><h1>Öğrenciler</h1><p>Öğrenci hesaplarını gerçek kullanıcı durumlarıyla arayın ve operasyonel bilgilerini inceleyin.</p></div></header><section className="admin-panel"><form className="admin-toolbar" onSubmit={e=>{e.preventDefault();setLoading(true);setError(false);setPage(0);setSubmitted(search.trim())}}><input aria-label="Öğrenci ara" placeholder="Ad veya e-posta ara" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Kullanıcı durumu" value={status} onChange={e=>{setLoading(true);setError(false);setStatus(e.target.value as UserStatus|"");setPage(0)}}><option value="">Tüm durumlar</option><option value="ACTIVE">Aktif</option><option value="SUSPENDED">Askıya alınmış</option><option value="DELETED">Silinmiş</option></select><button className="admin-button">Ara</button></form>{error?<div className="admin-error">Öğrenciler alınamadı.</div>:loading?<div className="admin-loading">Öğrenciler yükleniyor…</div>:users.length===0?<div className="admin-empty">Bu filtrelerle eşleşen öğrenci bulunmuyor.</div>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Öğrenci</th><th>Durum</th><th>E-posta doğrulama</th><th>Katılım</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}</small></td><td><span className={`admin-badge ${u.status==='ACTIVE'?'admin-badge--success':u.status==='SUSPENDED'?'admin-badge--warning':'admin-badge--danger'}`}>{labels[u.status]}</span></td><td>{u.emailVerified?'Doğrulandı':'Bekliyor'}</td><td>{new Date(u.createdAt).toLocaleDateString('tr-TR')}</td><td><button className="admin-button admin-button--secondary" type="button" onClick={()=>void open(u)}>Detay</button></td></tr>)}</tbody></table></div>}<div className="admin-pagination"><button className="admin-button admin-button--secondary" disabled={page===0} onClick={()=>{setLoading(true);setPage(p=>p-1)}}>Önceki</button><span>{page+1} / {pages}</span><button className="admin-button admin-button--secondary" disabled={page+1>=pages} onClick={()=>{setLoading(true);setPage(p=>p+1)}}>Sonraki</button></div></section>
    {selected&&<div className="admin-modal-backdrop"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="student-detail-title"><div className="admin-panel__heading"><h2 id="student-detail-title">{selected.user.name}</h2><button className="admin-button admin-button--secondary" type="button" onClick={()=>setSelected(null)}>Kapat</button></div><div className="admin-detail"><div className="admin-detail__facts"><div><span>E-posta</span><strong>{selected.user.email}</strong></div><div><span>Hesap</span><strong>{labels[selected.user.status]}</strong></div><div><span>E-posta doğrulama</span><strong>{selected.user.emailVerified?'Doğrulandı':'Bekliyor'}</strong></div><div><span>Yasal onboarding</span><strong>{selected.user.legalOnboardingCompleted?'Tamamlandı':'Bekliyor'}</strong></div></div><AdminProfilePhotoModeration name={selected.user.name} imageUrl={selected.profileImageUrl} assetId={selected.profileImageAssetId} onRemoved={()=>setSelected(current=>current?{...current,profileImageUrl:null,profileImageAssetId:null}:current)}/></div></section></div>}
  </main>;
};
