import { useEffect, useState } from "react";
import { coachApplicationAdminApi } from "../../coachApplications/coachApplicationAdminApi";
import type { CoachApplicationResponse, CoachApplicationStatus } from "../../coachApplications/coachApplicationTypes";
import "./admin.css";

const labels:Record<CoachApplicationStatus,string>={PENDING:"Bekliyor",APPROVED:"Onaylandı",REJECTED:"Reddedildi"};
export const AdminCoachApplicationsPage=()=>{const [status,setStatus]=useState<CoachApplicationStatus>('PENDING');const [items,setItems]=useState<CoachApplicationResponse[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [selected,setSelected]=useState<CoachApplicationResponse|null>(null);const [action,setAction]=useState<'APPROVE'|'REJECT'|null>(null);const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
useEffect(()=>{let active=true;coachApplicationAdminApi.list(status,0).then(response=>active&&setItems(response.content??[])).catch(()=>active&&setError(true)).finally(()=>active&&setLoading(false));return()=>{active=false}},[status]);
const submit=async()=>{if(!selected||!action||busy||(action==='REJECT'&&!reason.trim()))return;setBusy(true);try{if(action==='APPROVE')await coachApplicationAdminApi.approve(selected.id);else await coachApplicationAdminApi.reject(selected.id,reason.trim());setNotice(action==='APPROVE'?'Başvuru onaylandı ve koç hesabı oluşturuldu.':'Başvuru reddedildi.');setItems(current=>current.filter(item=>item.id!==selected.id));setSelected(null);setAction(null);setReason('')}catch{setNotice('İşlem tamamlanamadı. Lütfen yeniden deneyin.')}finally{setBusy(false)}};
return <main className="admin-page"><header className="admin-page__heading"><div><p className="admin-page__eyebrow">Koç edinimi</p><h1>Koç Başvuruları</h1><p>Adayların gönderdiği gerçek bilgileri inceleyip mevcut onay akışını yönetin.</p></div></header><section className="admin-panel"><div className="admin-tabs" role="tablist">{(Object.keys(labels) as CoachApplicationStatus[]).map(value=><button role="tab" aria-selected={status===value} className={status===value?'is-active':''} key={value} onClick={()=>{setLoading(true);setError(false);setStatus(value)}}>{labels[value]}</button>)}</div>{notice&&<p className={`admin-feedback ${notice.includes('tamamlanamadı')?'is-error':''}`}>{notice}</p>}{error?<div className="admin-error">Başvurular yüklenemedi.</div>:loading?<div className="admin-loading">Başvurular yükleniyor…</div>:items.length===0?<div className="admin-empty">Bu durumda başvuru yok.</div>:<div className="admin-card-list">{items.map(item=><article className="admin-card" key={item.id}><div className="admin-card__top"><div><h3>{item.fullName}</h3><small>{item.email}{item.phone?` · ${item.phone}`:''}</small></div><span className="admin-badge">{labels[item.status]}</span></div>{item.experience&&<p>{item.experience}</p>}{item.reviewNote&&<p><strong>Değerlendirme:</strong> {item.reviewNote}</p>}<div className="admin-actions"><button className="admin-button admin-button--secondary" onClick={()=>setSelected(item)}>Detayı incele</button>{item.status==='PENDING'&&<><button className="admin-button" onClick={()=>{setSelected(item);setAction('APPROVE')}}>Onayla</button><button className="admin-button admin-button--danger" onClick={()=>{setSelected(item);setAction('REJECT')}}>Reddet</button></>}</div></article>)}</div>}</section>
{selected&&<div className="admin-modal-backdrop"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="application-title"><div className="admin-panel__heading"><h2 id="application-title">{selected.fullName}</h2><button className="admin-button admin-button--secondary" onClick={()=>{setSelected(null);setAction(null)}}>Kapat</button></div><div className="admin-detail__facts"><div><span>E-posta</span><strong>{selected.email}</strong></div><div><span>Telefon</span><strong>{selected.phone??'—'}</strong></div><div><span>Başvuru tarihi</span><strong>{new Date(selected.createdAt).toLocaleDateString('tr-TR')}</strong></div><div><span>Durum</span><strong>{labels[selected.status]}</strong></div></div>{selected.experience&&<div><h3>Deneyim</h3><p>{selected.experience}</p></div>}{action&&<div className="admin-form"><p>{action==='APPROVE'?'Onay sonrasında koç hesabı ve gerekli profil sahipliği oluşturulacak. Devam edilsin mi?':'Başvuruyu reddetmek için açık bir gerekçe girin.'}</p>{action==='REJECT'&&<label>Red gerekçesi<textarea rows={4} value={reason} onChange={e=>setReason(e.target.value)} required/></label>}<div className="admin-actions"><button className="admin-button admin-button--secondary" onClick={()=>setAction(null)}>Vazgeç</button><button className={`admin-button ${action==='REJECT'?'admin-button--danger':''}`} disabled={busy||(action==='REJECT'&&!reason.trim())} onClick={()=>void submit()}>{busy?'İşleniyor…':action==='APPROVE'?'Onayı doğrula':'Reddi doğrula'}</button></div></div>}</section></div>}</main>};
